### ISSUE TITLE
numbered lists don't restart when interrupted

### ISSUE THREAD

**Issue by jgravois** [jbt/markdown-editor#44]
awesome work on this project.  its _super_ helpful to me on a regular basis!

just wanted to report that your own editor doesn't seem fussed about [interrupted lists](http://stackoverflow.com/questions/18088955/markdown-continue-numbered-list).  it would be cool if the behavior was a little more picky...

```
1. blah
2. blah blah
![alt-text](./skateboarder.png)  
]// without indenting the image, the numbering below should start from scratch
3.
```

**Comment by jbt** [comment]
This is the default behaviour of [markdown-it](https://github.com/markdown-it/markdown-it) which is the markdown parser the editor uses. As far as I can tell, this is the desired behaviour - it creates a new list but it tells it to start at 3 because that's the first number it sees. That's also the behaviour specified [in commonmark](http://spec.commonmark.org/dingus/?text=1.%20blah%0A2.%20blah%20blah%0A%0A!%5Balt-text%5D(.%2Fskateboarder.png)%20%20%0A%5D%2F%2F%20without%20indenting%20the%20image%2C%20the%20numbering%20below%20should%20start%20from%20scratch%0A%0A3.%20hi) too.

It looks like GitHub doesn't resume the list at 3, but if anything I'd say that's actually a bug on GitHub's side. So I'm tempted to say this is a wontfix, because this project doesn't *have* to mirror GitHub in every way.

How fussed are you about this?

**Comment by thorsummoner** [comment]
I personally would love to see the ability to choose a target markdown
engine, I use this tool to prepare semantic markup for docs that could be
dropped into any number of engines, most commonly github, or Python's
markdown library

**Comment by jgravois** [comment]
> How fussed are you about this?

to be honest, not very.  i respect where you're coming from.  since its a 'GitHub-Flavored' markdown editor, i thought it'd be helpful to document the inconsistency, but i'm also happy to report the inconsistent behavior in Github's parsing directly if you'd be kind enough to point me in the right direction (maybe [here](https://github.com/github/markup)? i'm not a ruby guy)

**Comment by thorsummoner** [comment]
There or possibly use github's contact link on the bottom of any page.
Their really good at getting back to community feedback
