### ISSUE TITLE
Is there a plan to add js-deflate feature in the new version?

### ISSUE THREAD

**Issue by athrunsun** [jbt/markdown-editor#81]
The original version (on branch [mdedit](https://github.com/jbt/markdown-editor/tree/mdedit)) has a very useful feature provided by [js-deflate](https://github.com/dankogai/js-deflate), which can gzip data to make it fit in URLs (see it in action [here](https://athrunsun.github.io/markdown-editor/)).

It's useful especially when you close your browser tab/window by accident, when you can really bring back everything by `Ctrl + Shift + T` (Chrome/Firefox). In this case it is not just reopening a closed tab, but restore markdown data because everything is hashed and appended to the URL!

So, is there a plan to add this feature in the new version?

**Comment by aero31aero** [comment]
Hey! That was a nifty feature indeed. However, since it was being computed on every keystroke, when you had a document with around, say, 10k characters or so, the lag was becoming noticeable and the editor felt too slow to work with.

As of now, I've pushed that feature into the share button.

![image](https://user-images.githubusercontent.com/8033238/34716595-575fc97c-f556-11e7-8ddf-ebc8b5f01ffd.png)

For your use case, what do you feel about an autosave feature that executes every couple of minutes or by the number of keystrokes.

**Comment by athrunsun** [comment]
@aero31aero Thank you for your reply!

The lag is a drawback indeed...

I love the "autosave" idea, and save every couple of minutes makes sense.
